In [1]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%config InlineBackend.figure_formats = ['svg']  # or svg
%matplotlib inline

sns.set()

# Building a baseline model using linear regression

In [1481]:
movies = pd.read_csv('.\data\EDA_data.csv')
movies.head()

,revenue,budget,runtime_minutes,genres_Adventure,genres_Animation,genres_Biography,genres_Comedy,genres_Crime,genres_Drama,genres_Horror,genres_other_genres,rating_PG-13,rating_R,distributor_Sony Pictures Entertainment (SPE),distributor_Twentieth Century Fox,distributor_Universal Pictures,distributor_Walt Disney Studios Motion Pictures,distributor_Warner Bros.,distributor_other_distributor
0,345141403,123000000.0,104.0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
1,546388108,125000000.0,123.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
2,460583960,103000000.0,155.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
3,328718434,140000000.0,130.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
4,330444045,55000000.0,108.0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0

In [1482]:
X1, y1 = movies.drop(['revenue', 'runtime_minutes',
       'genres_Adventure', 'genres_Animation', 'genres_Biography',
       'genres_Comedy', 'genres_Crime', 'genres_Drama', 'genres_Horror',
       'genres_other_genres', 'rating_PG-13', 'rating_R'],axis=1), movies['revenue']
X1.head()

,budget,distributor_Sony Pictures Entertainment (SPE),distributor_Twentieth Century Fox,distributor_Universal Pictures,distributor_Walt Disney Studios Motion Pictures,distributor_Warner Bros.,distributor_other_distributor
0,123000000.0,0,0,1,0,0,0
1,125000000.0,0,0,0,0,0,0
2,103000000.0,0,0,0,0,0,1
3,140000000.0,0,0,0,0,1,0
4,55000000.0,0,0,1,0,0,0

In [1483]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import (cross_val_score, train_test_split, 
                                     KFold, GridSearchCV)
# hold out 20% of the data for final testing
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=.2, random_state=10)

# Spliting the train data into 5 folds for cross validaion
kfold = KFold(n_splits=5, shuffle=True, random_state=0)

#Build a baseline model with linear regression
lm1 = LinearRegression()
scores = cross_val_score(lm1, X1_train, y1_train, cv=kfold)
print(scores)
print("Linear Reg Mean Score: ", np.mean(scores))

#Fitting the model
lm1.fit(X1_train, y1_train)

[0.50115883 0.49818494 0.52357431 0.53487856 0.5348144 ]
Linear Reg Mean Score:  0.5185222087786577

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [1484]:
lm1.score(X1_test,y1_test)

0.5453977071918905

In [1485]:
#The model performed better on the test set than the training set

Model Evaluation

In [1486]:
# Fitted vs. Actual on training data
#y1_pred = lm1.predict(X1_train)

[plt.scatter(y1_train, y1_pred, alpha=0.5)
plt.plot([0, 800000000], [0, 1000000000])
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title("Actual revenue vs Predicted revenue")]

SyntaxError: invalid syntax (<ipython-input-1486-e5ceb9f1171f>, line 5)

In [1487]:

# Fitted vs. Actual on test data
y_pred_test = lm1.predict(X1_test)

plt.scatter(y1_test, y_pred_test,alpha=0.5)
plt.plot([0, 1000000000], [0, 1000000000])
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title("Actual vs Predicted on test_data_set")

'\n# Fitted vs. Actual on test data\ny_pred_test = lm1.predict(X1_test)\n\nplt.scatter(y1_test, y_pred_test,alpha=0.5)\nplt.plot([0, 1000000000], [0, 1000000000])\nplt.xlabel(\'Actual\')\nplt.ylabel(\'Predicted\')\nplt.title("Actual vs Predicted on test_data_set")\n'

In [1488]:

# Plot Residuals vs. predicted

lin_reg_residuals = y1_train - y_pred

plt.scatter(y1_pred, lin_reg_residuals,alpha=0.5)
plt.plot([-100000000,1000000000], [0,0])
plt.title("Residuals vs. Predictions")

'\n# Plot Residuals vs. predicted\n\nlin_reg_residuals = y1_train - y_pred\n\nplt.scatter(y1_pred, lin_reg_residuals,alpha=0.5)\nplt.plot([-100000000,1000000000], [0,0])\nplt.title("Residuals vs. Predictions")\n'

# Further data adjustment and feature engineering

In [1183]:
# get rid of outliers

In [1184]:
column = movies['revenue']
print(column.max())
print(column.min())
print(column.mean())

2743577587
2530394
154344908.50359368

In [1185]:
column = movies['budget']
print(column.max())
print(column.min())
print(column.mean())

317000000.0
15000.0
52098565.88404408

In [1415]:
movies.nlargest(25, ['revenue'])

,revenue,budget,runtime_minutes,genres_Adventure,genres_Animation,genres_Biography,genres_Comedy,genres_Crime,genres_Drama,genres_Horror,genres_other_genres,rating_PG-13,rating_R,distributor_Sony Pictures Entertainment (SPE),distributor_Twentieth Century Fox,distributor_Universal Pictures,distributor_Walt Disney Studios Motion Pictures,distributor_Warner Bros.,distributor_other_distributor
1571,2743577587,237000000.0,162.0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
2598,2068223624,245000000.0,138.0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
2597,1670400637,150000000.0,124.0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0
2081,1518812988,220000000.0,143.0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
2601,1515047671,190000000.0,137.0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0
2599,1402805868,250000000.0,141.0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
2946,1332539889,317000000.0,152.0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
3118,1308467944,170000000.0,128.0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0
2954,1236005118,250000000.0,136.0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0
2251,1214811252,200000000.0,130.0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
2771,1153296293,250000000.0,147.0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
523,1140682011,94000000.0,201.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
1911,1123794079,195000000.0,154.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
2084,1108561013,200000000.0,143.0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0
2431,1104054072,210000000.0,165.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
2082,1081041287,250000000.0,164.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
1041,1066179725,225000000.0,151.0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
2770,1056057273,200000000.0,133.0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
1914,1045713802,250000000.0,137.0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0
1741,1025467110,200000000.0,108.0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1393,1003045358,185000000.0,152.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
180,974755371,125000000.0,152.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
2773,966550600,175000000.0,106.0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2962,962077546,90000000.0,119.0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0
1220,960996492,300000000.0,169.0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0

In [1187]:
movies.nsmallest(10, ['revenue'])

,revenue,budget,runtime_minutes,genres_Adventure,genres_Animation,genres_Biography,genres_Comedy,genres_Crime,genres_Drama,genres_Horror,genres_other_genres,rating_PG-13,rating_R,distributor_Sony Pictures Entertainment (SPE),distributor_Twentieth Century Fox,distributor_Universal Pictures,distributor_Walt Disney Studios Motion Pictures,distributor_Warner Bros.,distributor_other_distributor
2076,2530394,10000000.0,97.0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0
2074,2820490,5000000.0,97.0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1
1903,2908893,3000000.0,110.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
2415,2940411,2000000.0,80.0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1
175,3003296,44000000.0,95.0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0
171,3169930,14000000.0,112.0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1
2239,3332854,18000000.0,115.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2582,3485383,6000000.0,107.0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0
167,3548556,18000000.0,118.0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1
170,3728888,7000000.0,90.0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1

In [ ]:
#Check the distribution of the data

In [1188]:

def get_iqr_values(df_in, col_name):
    median = df_in[col_name].median()
    q1 = df_in[col_name].quantile(0.25) # 25th percentile / 1st quartile
    q3 = df_in[col_name].quantile(0.75) # 7th percentile / 3rd quartile
    iqr = q3-q1 #Interquartile range
    minimum  = q1-iqr # The minimum value or the |- marker in the box plot
    maximum = q3 + iqr # The maximum value or the -| marker in the box plot
    return median, q1, q3, iqr, minimum, maximum

def get_iqr_text(df_in, col_name):
    median, q1, q3, iqr, minimum, maximum = get_iqr_values(df_in, col_name)
    text = f"median={median:.2f}, q1={q1:.2f}, q3={q3:.2f}, iqr={iqr:.2f}, suggested_minimum={minimum:.2f}, sudgested_maximum={maximum:.2f}"
    return text

def remove_outliers(df_in, col_name, minimum, maxmimum):
    df_out = df_in.loc[(df_in[col_name] > minimum) & (df_in[col_name] < maximum)]
    return df_out

def count_outliers(df_in, col_name):
    _, _, _, _, minimum, maximum = get_iqr_values(df_in, col_name)
    df_outliers = df_in.loc[(df_in[col_name] <= minimum) | (df_in[col_name] >= maximum)]
    return df_outliers.shape[0]

def box_and_whisker(df_in, col_name):
    title = get_iqr_text(df_in, col_name)
    sns.boxplot(df_in[col_name])
    plt.title(title)
    plt.show()

In [1189]:
#box_and_whisker(movies, 'revenue')
text = get_iqr_text(movies, 'revenue')
print(text)

median=80547866.00, q1=35301209.50, q3=178783345.50, iqr=143482136.00, suggested_minimum=-108180926.50, sudgested_maximum=322265481.50

In [1416]:
new_movies = movies.loc[movies['revenue'] < 1500000000, :]
new_movies = new_movies.loc[new_movies['revenue'] > 10000000, :]
new_movies.shape

(1999, 19)

In [1417]:
#check for skewness
from scipy.stats import skew
print(skew(new_movies['revenue']))

#plt.figure()
#sns.distplot(movies['revenue'])
#plt.show()

2.6192363083322303

In [1418]:

#very high posoive skewness
#lets correct it by applying a log transformation
y = np.log(new_movies['revenue'])
skew(y)

0.13341215861490488

In [1366]:
# Add a new feature - Running_time

In [1419]:
X2 = new_movies.drop(['revenue','genres_Adventure', 'genres_Animation', 'genres_Biography',
       'genres_Comedy', 'genres_Crime', 'genres_Drama', 'genres_Horror',
       'genres_other_genres', 'rating_PG-13', 'rating_R'],axis=1)
X2.head()

,budget,runtime_minutes,distributor_Sony Pictures Entertainment (SPE),distributor_Twentieth Century Fox,distributor_Universal Pictures,distributor_Walt Disney Studios Motion Pictures,distributor_Warner Bros.,distributor_other_distributor
0,123000000.0,104.0,0,0,1,0,0,0
1,125000000.0,123.0,0,0,0,0,0,0
2,103000000.0,155.0,0,0,0,0,0,1
3,140000000.0,130.0,0,0,0,0,1,0
4,55000000.0,108.0,0,0,1,0,0,0

In [1420]:
# hold out 20% of the data for final testing
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y, test_size=.2, random_state=10)

# Spliting the train data into 5 folds for cross validaion
kfold = KFold(n_splits=5, shuffle=True, random_state=0)

#Building a linear regression model
lm2 = LinearRegression()
scores = cross_val_score(lm2, X2_train, y2_train, cv=kfold)
print(scores)
print("Linear Reg Mean Score: ", np.mean(scores))
lm2.fit(X2_train, y2_train)

[0.43520689 0.49743458 0.51738597 0.4464944  0.46487202]
Linear Reg Mean Score:  0.47227877234679844

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [1421]:
lm2.score(X2_test,y2_test)

0.4617678837692991

In [1255]:
# Fitted vs. Actual on training data
[y2_pred = lm2.predict(X2_train)

plt.scatter(y2_train, y2_pred, alpha=0.5)
plt.plot([0, 800000000], [0, 1000000000])
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title("Actual revenue vs Predicted revenue")]

SyntaxError: invalid syntax (<ipython-input-1255-f880ca8fbb9d>, line 2)

In [1256]:
# Plot Residuals vs. predicted
[lin_reg_residuals = y2_train - y2_pred

plt.scatter(y2_pred, lin_reg_residuals,alpha=0.5)
plt.plot([-100000000,1000000000], [0,0])
plt.title("Residuals vs. Predictions")]

SyntaxError: invalid syntax (<ipython-input-1256-1ebeac44c86f>, line 2)

In [1257]:
# Add a new feature - genres  'rating_PG-13', 'rating_R'

In [1422]:
X3 = new_movies.drop(['revenue','rating_PG-13', 'rating_R',],axis=1)

X3.head()

,budget,runtime_minutes,genres_Adventure,genres_Animation,genres_Biography,genres_Comedy,genres_Crime,genres_Drama,genres_Horror,genres_other_genres,distributor_Sony Pictures Entertainment (SPE),distributor_Twentieth Century Fox,distributor_Universal Pictures,distributor_Walt Disney Studios Motion Pictures,distributor_Warner Bros.,distributor_other_distributor
0,123000000.0,104.0,0,0,0,1,0,0,0,0,0,0,1,0,0,0
1,125000000.0,123.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,103000000.0,155.0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,140000000.0,130.0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,55000000.0,108.0,0,0,0,1,0,0,0,0,0,0,1,0,0,0

In [1423]:
# hold out 20% of the data for final testing
X3_train, X3_test, y_train, y_test = train_test_split(X3, y, test_size=.2, random_state=10)

# Spliting the train data into 5 folds for cross validaion
kfold = KFold(n_splits=5, shuffle=True, random_state=0)

#Building a linear regression model
lm3 = LinearRegression()
scores = cross_val_score(lm3, X3_train, y_train, cv=kfold)
print(scores)
print("Linear Reg Mean Score: ", np.mean(scores))
lm3.fit(X3_train, y_train)

[0.44705116 0.50090584 0.52074614 0.45699997 0.47072483]
Linear Reg Mean Score:  0.4792855889036124

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [1424]:
lm3.score(X3_test,y_test)

0.4605816454270679

In [1261]:
#Add a new feature - rating

In [1425]:
X = new_movies.drop(['revenue'],axis=1)
X.head()

,budget,runtime_minutes,genres_Adventure,genres_Animation,genres_Biography,genres_Comedy,genres_Crime,genres_Drama,genres_Horror,genres_other_genres,rating_PG-13,rating_R,distributor_Sony Pictures Entertainment (SPE),distributor_Twentieth Century Fox,distributor_Universal Pictures,distributor_Walt Disney Studios Motion Pictures,distributor_Warner Bros.,distributor_other_distributor
0,123000000.0,104.0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
1,125000000.0,123.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
2,103000000.0,155.0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
3,140000000.0,130.0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
4,55000000.0,108.0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0

In [1427]:
# hold out 20% of the data for final testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=10)

# Spliting the train data into 5 folds for cross validaion
kfold = KFold(n_splits=5, shuffle=True, random_state=0)

#Building a linear regression model
lm = LinearRegression()
scores = cross_val_score(lm, X_train, y_train, cv=kfold)
print(scores)
print("Linear Reg Mean Score: ", np.mean(scores))
lm.fit(X_train, y_train)

[0.44492242 0.50293925 0.52373109 0.46253557 0.46794896]
Linear Reg Mean Score:  0.48041545795052054

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [1428]:
lm.score(X_test,y_test)

0.4582384264764612

In [1429]:
y_preds = lm.predict(X_test)

In [1430]:
mean_absolute_error(y_test,y_preds)

0.6765341356506701

In [1267]:
# Fitted vs. Actual on training data
[y_pred = lm.predict(X_train)

plt.scatter(y_train, y_pred, alpha=0.5)
#plt.plot([0, 800000000], [0, 1000000000])
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title("Actual revenue vs Predicted revenue")]

SyntaxError: invalid syntax (<ipython-input-1267-5988c09e1ff6>, line 2)

In [1268]:
# Fitted vs. Actual on test data
#y_pred_test = lm.predict(X_test)

plt.scatter(y_test, y_pred_test,alpha=0.5)
plt.plot([0, 1000000000], [0, 1000000000])
plt.xlabel('Actual')
plt.ylabel('Predicted')
plt.title("Actual vs Predicted on test_data_set")

SyntaxError: invalid syntax (<ipython-input-1268-6c5927ccf899>, line 8)

In [693]:
# Plot Residuals vs. predicted
#y_pred_test = lm.predict(X_test)
lin_reg_residuals = y_test - y_pred_test

plt.scatter(y_pred_test, lin_reg_residuals,alpha=0.5)
plt.plot([17,21], [0,0])
plt.title("Residuals vs. Predictions")
plt.xlabel('Actual')
plt.ylabel('Predicted')

SyntaxError: invalid syntax (<ipython-input-693-871ac52fd912>, line 7)

Evaluation 

#The model's r2 on the test set increased with the new feature added  
#The model is still overfitting
#To improve that we will do a regularizaion

# Regularization

In [1431]:
from sklearn import linear_model
from sklearn.linear_model import LinearRegression, Ridge, Lasso, LassoCV, RidgeCV
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
pd.options.display.max_columns = None
%matplotlib inline
from IPython.display import display

In [1432]:
#Scalling the data
scaler = StandardScaler()

x_train_scaled= scaler.fit_transform(X_train.values)
X_test_scaled= scaler.transform(X_test.values)

In [1435]:
x_train = pd.DataFrame(x_train_scaled)

In [1437]:
x_train.shape

(1599, 18)

In [1438]:
y_train.shape

(1599,)

In [1439]:
alphavec = 10**np.linspace(-2,2,200)
lasso_model = LassoCV(alphas = alphavec, cv=5)
lasso_model.fit(X_train, y_train)

LassoCV(alphas=array([1.00000000e-02, 1.04737090e-02, 1.09698580e-02, 1.14895100e-02,
       1.20337784e-02, 1.26038293e-02, 1.32008840e-02, 1.38262217e-02,
       1.44811823e-02, 1.51671689e-02, 1.58856513e-02, 1.66381689e-02,
       1.74263339e-02, 1.82518349e-02, 1.91164408e-02, 2.00220037e-02,
       2.09704640e-02, 2.19638537e-02, 2.30043012e-02, 2.40940356e-02,
       2.52353917e-02, 2.64308149e-0...
       6.01027678e+01, 6.29498899e+01, 6.59318827e+01, 6.90551352e+01,
       7.23263390e+01, 7.57525026e+01, 7.93409667e+01, 8.30994195e+01,
       8.70359136e+01, 9.11588830e+01, 9.54771611e+01, 1.00000000e+02]),
        copy_X=True, cv=5, eps=0.001, fit_intercept=True, max_iter=1000,
        n_alphas=100, n_jobs=None, normalize=False, positive=False,
        precompute='auto', random_state=None, selection='cyclic', tol=0.0001,
        verbose=False)

In [1440]:
list(zip(X_train.columns, lasso_model.coef_))

[('budget', 1.3122391622849242e-08),
 ('runtime_minutes', 0.006112890214918336),
 ('genres_Adventure', 0.0),
 ('genres_Animation', 0.0),
 ('genres_Biography', -0.0),
 ('genres_Comedy', -0.0),
 ('genres_Crime', -0.0),
 ('genres_Drama', -0.04882957741617074),
 ('genres_Horror', 0.11188683457428869),
 ('genres_other_genres', 0.0),
 ('rating_PG-13', 0.0),
 ('rating_R', -0.06458184403168224),
 ('distributor_Sony Pictures Entertainment (SPE)', 0.0),
 ('distributor_Twentieth Century Fox', 0.12024343328666441),
 ('distributor_Universal Pictures', 0.1168351677662735),
 ('distributor_Walt Disney Studios Motion Pictures', -0.0),
 ('distributor_Warner Bros.', -0.0),
 ('distributor_other_distributor', -0.19538263298719966)]

In [1443]:
#intrerpreting the coefficients(This is needed because the target variable had a log transformaion)
import math
budget = (math.exp(1.3122391622849242e-08) - 1) * 100 
print(budget)
runtime_minutes = (math.exp(0.006112890214918336) - 1) * 100 
print(runtime_minutes)
genres_Drama = (math.exp(-0.04882957741617074) - 1) * 100 
print(genres_Drama)
genres_Horror = (math.exp(0.11188683457428869) - 1) * 100
print(genres_Horror)

1.312239161777029e-06
0.6131612057055813
-4.76565833048066
11.838629082280573

In [1445]:
scores = cross_val_score(lasso_model, X_train, y_train, cv=kfold)

In [1446]:
print(scores)
print(scores.mean())

[0.44393893 0.49915659 0.52311633 0.44678714 0.46888241]
0.47637628063523324

In [1455]:
lasso_model.score(X_test,y_test)

0.47355932010070134

In [1449]:
from sklearn.metrics import mean_absolute_error

In [1452]:
y_pred = lasso_model.predict(X_test)

In [1453]:
MAE = mean_absolute_error(y_test,y_pred)
MAE

0.662922488657275

In [1360]:
#Actual vs predicted on test set
#plt.scatter(y_pred, y_test)
#plt.plot([17,21], [16,21])
#plt.title("Residuals vs. Predictions")

In [1350]:
# Plot Residuals vs. predicted

lasso_reg_residuals = y_test - y_pred

#plt.scatter(y_pred, lasso_reg_residuals,alpha=0.5)
#plt.plot([17,21], [0,0])
#plt.title("Residuals vs. Predictions")

In [1467]:
#ridge regularization
ridge_model = Ridge(alpha = 0.5)
ridge_model.fit(X_train, y_train)

list(zip(X_train.columns, lr_model_ridge.coef_))

C:\Users\BereketSharew\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=2.02155e-18): result may not be accurate.
  overwrite_a=True).T

[('budget', 1.2383014219349912e-08),
 ('runtime_minutes', 0.008202548719288301),
 ('genres_Adventure', 0.08033324999658602),
 ('genres_Animation', 0.11626809269287862),
 ('genres_Biography', -0.1492537069548378),
 ('genres_Comedy', -0.04183590917840805),
 ('genres_Crime', -0.15037963485407363),
 ('genres_Drama', -0.15959395078978886),
 ('genres_Horror', 0.3005665449249468),
 ('genres_other_genres', 0.20349852683993563),
 ('rating_PG-13', -0.023724492910749573),
 ('rating_R', -0.1398707898160156),
 ('distributor_Sony Pictures Entertainment (SPE)', 0.13621184901458802),
 ('distributor_Twentieth Century Fox', 0.2779273564212247),
 ('distributor_Universal Pictures', 0.2887598906995394),
 ('distributor_Walt Disney Studios Motion Pictures', -0.026422754278726507),
 ('distributor_Warner Bros.', 0.08218013715820525),
 ('distributor_other_distributor', -0.1347313985422708)]

In [1468]:
scores = cross_val_score(lr_model_ridge, X_train, y_train, cv=kfold)
print(scores)
print("Ridge Mean Score: ", np.mean(scores))
lr_model_ridge.fit(X_train, y_train)

[0.44517049 0.50296041 0.52382726 0.46250299 0.46808911]
Ridge Mean Score:  0.4805100535720168

C:\Users\BereketSharew\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.76177e-18): result may not be accurate.
  overwrite_a=True).T
C:\Users\BereketSharew\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=2.09197e-18): result may not be accurate.
  overwrite_a=True).T
C:\Users\BereketSharew\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=2.09598e-18): result may not be accurate.
  overwrite_a=True).T
C:\Users\BereketSharew\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=1.96637e-18): result may not be accurate.
  overwrite_a=True).T
C:\Users\BereketSharew\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=2.3224e-18): result may not be accurate.
  overwrite_a=True).T
C:\Users\BereketSharew\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=2.02155e-18): result may not be accurate.
  overwrite_a=True).T

Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [1469]:
ridge_model.score(X_test,y_test)

0.4584712631412101